from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_challan_pdf(challan_data, output_dir=r'D:\traffic_violation_system\output'):
    os.makedirs(output_dir, exist_ok=True)
    
    filename = f"{output_dir}\\challan_{challan_data['challan_id']}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4)
    
    styles = getSampleStyleSheet()
    elements = []

    # Header style
    header_style = ParagraphStyle(
        'header',
        parent=styles['Title'],
        fontSize=20,
        textColor=colors.darkblue,
        spaceAfter=5
    )
    sub_style = ParagraphStyle(
        'sub',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.grey,
        spaceAfter=20,
        alignment=1
    )

    # Government Header
    elements.append(Paragraph("🚔 TRAFFIC POLICE DEPARTMENT", header_style))
    elements.append(Paragraph("E-Challan — Digital Traffic Violation Notice", sub_style))
    elements.append(Spacer(1, 0.2*inch))

    # Challan details table
    challan_info = [
        ['Challan ID', challan_data['challan_id']],
        ['Date & Time', challan_data['timestamp']],
        ['Location', challan_data.get('location', 'Camera ID: CAM-01')],
        ['Vehicle Number', challan_data['vehicle_number']],
        ['Status', 'UNPAID'],
    ]

    table = Table(challan_info, colWidths=[2.5*inch, 4*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.lightblue),
        ('TEXTCOLOR', (0,0), (0,-1), colors.darkblue),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 11),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('ROWBACKGROUNDS', (1,0), (1,-1), [colors.white, colors.lightyellow]),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.3*inch))

    # Violations table
    elements.append(Paragraph("Violations Detected:", styles['Heading2']))
    
    violation_data = [['#', 'Violation', 'Fine Amount']]
    for i, v in enumerate(challan_data['violations'], 1):
        violation_data.append([
            str(i),
            v['description'],
            f"Rs. {v['fine']}"
        ])
    violation_data.append(['', 'TOTAL FINE', f"Rs. {challan_data['total_fine']}"])

    vtable = Table(violation_data, colWidths=[0.5*inch, 4*inch, 2*inch])
    vtable.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,-1), (-1,-1), 'Helvetica-Bold'),
        ('BACKGROUND', (0,-1), (-1,-1), colors.lightcoral),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('FONTSIZE', (0,0), (-1,-1), 11),
        ('PADDING', (0,0), (-1,-1), 8),
        ('ROWBACKGROUNDS', (0,1), (-1,-2), [colors.white, colors.lightyellow]),
    ]))
    elements.append(vtable)
    elements.append(Spacer(1, 0.3*inch))

    # Footer
    footer_style = ParagraphStyle(
        'footer',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.grey,
        alignment=1
    )
    elements.append(Paragraph("Pay fine within 30 days to avoid legal action.", footer_style))
    elements.append(Paragraph("Generated by AI-powered Traffic Violation Detection System", footer_style))

    doc.build(elements)
    print(f"Challan generated: {filename}")
    return filename